<?php

namespace AppBundle\Repository;

/**
 * ProductCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCatRepository extends \Doctrine\ORM\EntityRepository
{
}
